In [14]:
import math
import numpy as np

In [16]:
matrix = np.array([[1, 2,4],[2,3,11]])
print(matrix, "\n")

transposed = matrix.T
print(transposed, "\n")

# matrix multiplication

answer = matrix @ transposed

answer_ = transposed@matrix

print(answer, "\n \n", answer_ , '\n')

[[ 1  2  4]
 [ 2  3 11]] 

[[ 1  2]
 [ 2  3]
 [ 4 11]] 

[[ 21  52]
 [ 52 134]] 
 
 [[  5   8  26]
 [  8  13  41]
 [ 26  41 137]] 

